/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "roo_transceivers.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(roo_transceivers_Descriptor, roo_transceivers_Descriptor, 2)


PB_BIND(roo_transceivers_Descriptor_Sensor, roo_transceivers_Descriptor_Sensor, AUTO)


PB_BIND(roo_transceivers_Descriptor_Actuator, roo_transceivers_Descriptor_Actuator, AUTO)


PB_BIND(roo_transceivers_ClientMessage, roo_transceivers_ClientMessage, AUTO)


PB_BIND(roo_transceivers_ClientMessage_RequestUpdate, roo_transceivers_ClientMessage_RequestUpdate, AUTO)


PB_BIND(roo_transceivers_ClientMessage_RequestState, roo_transceivers_ClientMessage_RequestState, AUTO)


PB_BIND(roo_transceivers_ClientMessage_Write, roo_transceivers_ClientMessage_Write, AUTO)


PB_BIND(roo_transceivers_ServerMessage, roo_transceivers_ServerMessage, 2)


PB_BIND(roo_transceivers_ServerMessage_Init, roo_transceivers_ServerMessage_Init, AUTO)


PB_BIND(roo_transceivers_ServerMessage_UpdateBegin, roo_transceivers_ServerMessage_UpdateBegin, AUTO)


PB_BIND(roo_transceivers_ServerMessage_DescriptorAdded, roo_transceivers_ServerMessage_DescriptorAdded, 2)


PB_BIND(roo_transceivers_ServerMessage_DescriptorRemoved, roo_transceivers_ServerMessage_DescriptorRemoved, AUTO)


PB_BIND(roo_transceivers_ServerMessage_DeviceAdded, roo_transceivers_ServerMessage_DeviceAdded, AUTO)


PB_BIND(roo_transceivers_ServerMessage_DeviceRemoved, roo_transceivers_ServerMessage_DeviceRemoved, AUTO)


PB_BIND(roo_transceivers_ServerMessage_DevicePreserved, roo_transceivers_ServerMessage_DevicePreserved, AUTO)


PB_BIND(roo_transceivers_ServerMessage_DeviceModified, roo_transceivers_ServerMessage_DeviceModified, AUTO)


PB_BIND(roo_transceivers_ServerMessage_UpdateEnd, roo_transceivers_ServerMessage_UpdateEnd, AUTO)


PB_BIND(roo_transceivers_ServerMessage_ReadingsBegin, roo_transceivers_ServerMessage_ReadingsBegin, AUTO)


PB_BIND(roo_transceivers_ServerMessage_ReadingsEnd, roo_transceivers_ServerMessage_ReadingsEnd, AUTO)


PB_BIND(roo_transceivers_ServerMessage_Reading, roo_transceivers_ServerMessage_Reading, 2)


PB_BIND(roo_transceivers_ServerMessage_Reading_SensorValue, roo_transceivers_ServerMessage_Reading_SensorValue, AUTO)





