/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ROO_TRANSCEIVERS_ROO_TRANSCEIVERS_PB_H_INCLUDED
#define PB_ROO_TRANSCEIVERS_ROO_TRANSCEIVERS_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _roo_transceivers_Quantity {
    roo_transceivers_Quantity_kUnspecifiedQuantity = 0,
    /* Fundamental. */
    roo_transceivers_Quantity_kElapsedTime = 1, /* [seconds]. */
    roo_transceivers_Quantity_kMass = 2, /* [kilograms]. */
    roo_transceivers_Quantity_kTemperature = 3, /* [deg C]. */
    roo_transceivers_Quantity_kFrequency = 4, /* [Hz]. */
    roo_transceivers_Quantity_kLength = 5, /* [m]. */
    roo_transceivers_Quantity_kAngle = 6, /* [rad]. */
    /* Displacement. */
    roo_transceivers_Quantity_kDistance = 10, /* [m]. */
    roo_transceivers_Quantity_kVelocity = 11, /* [m/s]. */
    roo_transceivers_Quantity_kAcceleration = 12, /* [m/s^2]. */
    roo_transceivers_Quantity_kJerk = 13, /* [m/s^3]. */
    /* Force and energy. */
    roo_transceivers_Quantity_kForce = 20, /* [N]. */
    roo_transceivers_Quantity_kPressure = 21, /* [Pa]. */
    roo_transceivers_Quantity_kEnergy = 22, /* [J]. */
    roo_transceivers_Quantity_kPower = 23, /* [W]. */
    /* Spatial. */
    roo_transceivers_Quantity_kArea = 30, /* [m^2]. */
    roo_transceivers_Quantity_kVolume = 31, /* [m^3]. */
    /* Liquids. */
    roo_transceivers_Quantity_kLiquidVolume = 40, /* [liter]. */
    roo_transceivers_Quantity_kLiquidFlow = 41, /* [liter/min]. */
    /* Thermodynamics. */
    roo_transceivers_Quantity_kHeat = 50, /* [J]. */
    /* Magnetism. */
    roo_transceivers_Quantity_kMagneticFlux = 60, /* [We]. */
    /* Electricity. */
    roo_transceivers_Quantity_kElectricCharge = 70, /* [C]. */
    roo_transceivers_Quantity_kElectricCurrent = 71, /* [A]. */
    roo_transceivers_Quantity_kVoltage = 72, /* [V]. */
    roo_transceivers_Quantity_kResistance = 73, /* [Ohm]. */
    roo_transceivers_Quantity_kImpedance = 74, /* [Ohm]. */
    roo_transceivers_Quantity_kCapacitance = 75, /* [F]. */
    roo_transceivers_Quantity_kInductance = 76, /* [T]. */
    /* Light. */
    roo_transceivers_Quantity_kLuminousIntensity = 90, /* [lumen]. */
    roo_transceivers_Quantity_kColorHue = 95, /* [0-360). */
    roo_transceivers_Quantity_kColorSaturation = 96, /* [0-1]. */
    roo_transceivers_Quantity_kColorBrightness = 97, /* [0-1]. */
    /* Geolocation. */
    roo_transceivers_Quantity_kLatitude = 110, /* [-90-90] (North is positive). */
    roo_transceivers_Quantity_kLongitude = 111, /* [-180-180] (East is positive). */
    roo_transceivers_Quantity_kAltitude = 112, /* [m]. */
    /* Environmental. */
    roo_transceivers_Quantity_kAirHumidity = 130, /* [%]. */
    /* Generic control. */
    roo_transceivers_Quantity_kBinaryState = 150, /* on/off (0.0 or 1.0). */
    roo_transceivers_Quantity_kMultiState = 151
} roo_transceivers_Quantity;

/* Struct definitions */
typedef struct _roo_transceivers_Descriptor_Sensor {
    char id[24];
    roo_transceivers_Quantity quantity;
} roo_transceivers_Descriptor_Sensor;

typedef struct _roo_transceivers_Descriptor_Actuator {
    char id[24];
    roo_transceivers_Quantity quantity;
} roo_transceivers_Descriptor_Actuator;

typedef struct _roo_transceivers_Descriptor {
    pb_size_t sensors_count;
    roo_transceivers_Descriptor_Sensor sensors[16];
    pb_size_t actuators_count;
    roo_transceivers_Descriptor_Actuator actuators[16];
} roo_transceivers_Descriptor;

typedef struct _roo_transceivers_ClientMessage_RequestUpdate {
    char dummy_field;
} roo_transceivers_ClientMessage_RequestUpdate;

typedef struct _roo_transceivers_ClientMessage_RequestState {
    char dummy_field;
} roo_transceivers_ClientMessage_RequestState;

typedef struct _roo_transceivers_ClientMessage_Write {
    char device_locator_schema[16];
    char device_locator_id[24];
    char device_locator_actuator_id[24];
    float value;
} roo_transceivers_ClientMessage_Write;

typedef struct _roo_transceivers_ClientMessage {
    pb_size_t which_contents;
    union {
        roo_transceivers_ClientMessage_RequestUpdate request_update;
        roo_transceivers_ClientMessage_RequestState request_state;
        roo_transceivers_ClientMessage_Write write;
    } contents;
} roo_transceivers_ClientMessage;

typedef struct _roo_transceivers_ServerMessage_UpdateBegin {
    bool delta;
} roo_transceivers_ServerMessage_UpdateBegin;

typedef struct _roo_transceivers_ServerMessage_DescriptorAdded {
    uint32_t key;
    bool has_descriptor;
    roo_transceivers_Descriptor descriptor;
} roo_transceivers_ServerMessage_DescriptorAdded;

typedef struct _roo_transceivers_ServerMessage_DescriptorRemoved {
    uint32_t key;
} roo_transceivers_ServerMessage_DescriptorRemoved;

typedef struct _roo_transceivers_ServerMessage_DeviceAdded {
    char locator_schema[16];
    char locator_id[24];
    uint32_t descriptor_key;
} roo_transceivers_ServerMessage_DeviceAdded;

typedef struct _roo_transceivers_ServerMessage_DeviceRemoved {
    uint32_t prev_index;
} roo_transceivers_ServerMessage_DeviceRemoved;

typedef struct _roo_transceivers_ServerMessage_DevicePreserved {
    uint32_t prev_index;
    bool has_count;
    uint32_t count;
} roo_transceivers_ServerMessage_DevicePreserved;

typedef struct _roo_transceivers_ServerMessage_DeviceModified {
    uint32_t prev_index;
    uint32_t descriptor_key;
} roo_transceivers_ServerMessage_DeviceModified;

typedef struct _roo_transceivers_ServerMessage_UpdateEnd {
    char dummy_field;
} roo_transceivers_ServerMessage_UpdateEnd;

typedef struct _roo_transceivers_ServerMessage_ReadingsBegin {
    char dummy_field;
} roo_transceivers_ServerMessage_ReadingsBegin;

typedef struct _roo_transceivers_ServerMessage_ReadingsEnd {
    char dummy_field;
} roo_transceivers_ServerMessage_ReadingsEnd;

typedef struct _roo_transceivers_ServerMessage_Reading_SensorValue {
    char device_locator_sensor_id[24];
    float value;
    uint64_t age_ms;
} roo_transceivers_ServerMessage_Reading_SensorValue;

typedef struct _roo_transceivers_ServerMessage_Reading {
    char device_locator_schema[16];
    char device_locator_id[24];
    pb_size_t sensor_values_count;
    roo_transceivers_ServerMessage_Reading_SensorValue sensor_values[16];
} roo_transceivers_ServerMessage_Reading;

typedef struct _roo_transceivers_ServerMessage {
    pb_size_t which_contents;
    union {
        roo_transceivers_ServerMessage_UpdateBegin transceiver_update_begin;
        roo_transceivers_ServerMessage_DescriptorAdded descriptor_added;
        roo_transceivers_ServerMessage_DescriptorRemoved descriptor_removed;
        /* Device device = 4; */
        roo_transceivers_ServerMessage_DeviceAdded device_added;
        roo_transceivers_ServerMessage_DeviceRemoved device_removed;
        roo_transceivers_ServerMessage_DevicePreserved device_preserved;
        roo_transceivers_ServerMessage_DeviceModified device_modified;
        roo_transceivers_ServerMessage_UpdateEnd transceiver_update_end;
        roo_transceivers_ServerMessage_ReadingsBegin readings_begin;
        roo_transceivers_ServerMessage_Reading reading;
        roo_transceivers_ServerMessage_ReadingsEnd readings_end;
    } contents;
} roo_transceivers_ServerMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _roo_transceivers_Quantity_MIN roo_transceivers_Quantity_kUnspecifiedQuantity
#define _roo_transceivers_Quantity_MAX roo_transceivers_Quantity_kMultiState
#define _roo_transceivers_Quantity_ARRAYSIZE ((roo_transceivers_Quantity)(roo_transceivers_Quantity_kMultiState+1))


#define roo_transceivers_Descriptor_Sensor_quantity_ENUMTYPE roo_transceivers_Quantity

#define roo_transceivers_Descriptor_Actuator_quantity_ENUMTYPE roo_transceivers_Quantity



















/* Initializer values for message structs */
#define roo_transceivers_Descriptor_init_default {0, {roo_transceivers_Descriptor_Sensor_init_default, roo_transceivers_Descriptor_Sensor_init_default, roo_transceivers_Descriptor_Sensor_init_default, roo_transceivers_Descriptor_Sensor_init_default, roo_transceivers_Descriptor_Sensor_init_default, roo_transceivers_Descriptor_Sensor_init_default, roo_transceivers_Descriptor_Sensor_init_default, roo_transceivers_Descriptor_Sensor_init_default, roo_transceivers_Descriptor_Sensor_init_default, roo_transceivers_Descriptor_Sensor_init_default, roo_transceivers_Descriptor_Sensor_init_default, roo_transceivers_Descriptor_Sensor_init_default, roo_transceivers_Descriptor_Sensor_init_default, roo_transceivers_Descriptor_Sensor_init_default, roo_transceivers_Descriptor_Sensor_init_default, roo_transceivers_Descriptor_Sensor_init_default}, 0, {roo_transceivers_Descriptor_Actuator_init_default, roo_transceivers_Descriptor_Actuator_init_default, roo_transceivers_Descriptor_Actuator_init_default, roo_transceivers_Descriptor_Actuator_init_default, roo_transceivers_Descriptor_Actuator_init_default, roo_transceivers_Descriptor_Actuator_init_default, roo_transceivers_Descriptor_Actuator_init_default, roo_transceivers_Descriptor_Actuator_init_default, roo_transceivers_Descriptor_Actuator_init_default, roo_transceivers_Descriptor_Actuator_init_default, roo_transceivers_Descriptor_Actuator_init_default, roo_transceivers_Descriptor_Actuator_init_default, roo_transceivers_Descriptor_Actuator_init_default, roo_transceivers_Descriptor_Actuator_init_default, roo_transceivers_Descriptor_Actuator_init_default, roo_transceivers_Descriptor_Actuator_init_default}}
#define roo_transceivers_Descriptor_Sensor_init_default {"", _roo_transceivers_Quantity_MIN}
#define roo_transceivers_Descriptor_Actuator_init_default {"", _roo_transceivers_Quantity_MIN}
#define roo_transceivers_ClientMessage_init_default {0, {roo_transceivers_ClientMessage_RequestUpdate_init_default}}
#define roo_transceivers_ClientMessage_RequestUpdate_init_default {0}
#define roo_transceivers_ClientMessage_RequestState_init_default {0}
#define roo_transceivers_ClientMessage_Write_init_default {"", "", "", 0}
#define roo_transceivers_ServerMessage_init_default {0, {roo_transceivers_ServerMessage_UpdateBegin_init_default}}
#define roo_transceivers_ServerMessage_UpdateBegin_init_default {0}
#define roo_transceivers_ServerMessage_DescriptorAdded_init_default {0, false, roo_transceivers_Descriptor_init_default}
#define roo_transceivers_ServerMessage_DescriptorRemoved_init_default {0}
#define roo_transceivers_ServerMessage_DeviceAdded_init_default {"", "", 0}
#define roo_transceivers_ServerMessage_DeviceRemoved_init_default {0}
#define roo_transceivers_ServerMessage_DevicePreserved_init_default {0, false, 0}
#define roo_transceivers_ServerMessage_DeviceModified_init_default {0, 0}
#define roo_transceivers_ServerMessage_UpdateEnd_init_default {0}
#define roo_transceivers_ServerMessage_ReadingsBegin_init_default {0}
#define roo_transceivers_ServerMessage_ReadingsEnd_init_default {0}
#define roo_transceivers_ServerMessage_Reading_init_default {"", "", 0, {roo_transceivers_ServerMessage_Reading_SensorValue_init_default, roo_transceivers_ServerMessage_Reading_SensorValue_init_default, roo_transceivers_ServerMessage_Reading_SensorValue_init_default, roo_transceivers_ServerMessage_Reading_SensorValue_init_default, roo_transceivers_ServerMessage_Reading_SensorValue_init_default, roo_transceivers_ServerMessage_Reading_SensorValue_init_default, roo_transceivers_ServerMessage_Reading_SensorValue_init_default, roo_transceivers_ServerMessage_Reading_SensorValue_init_default, roo_transceivers_ServerMessage_Reading_SensorValue_init_default, roo_transceivers_ServerMessage_Reading_SensorValue_init_default, roo_transceivers_ServerMessage_Reading_SensorValue_init_default, roo_transceivers_ServerMessage_Reading_SensorValue_init_default, roo_transceivers_ServerMessage_Reading_SensorValue_init_default, roo_transceivers_ServerMessage_Reading_SensorValue_init_default, roo_transceivers_ServerMessage_Reading_SensorValue_init_default, roo_transceivers_ServerMessage_Reading_SensorValue_init_default}}
#define roo_transceivers_ServerMessage_Reading_SensorValue_init_default {"", 0, 0}
#define roo_transceivers_Descriptor_init_zero    {0, {roo_transceivers_Descriptor_Sensor_init_zero, roo_transceivers_Descriptor_Sensor_init_zero, roo_transceivers_Descriptor_Sensor_init_zero, roo_transceivers_Descriptor_Sensor_init_zero, roo_transceivers_Descriptor_Sensor_init_zero, roo_transceivers_Descriptor_Sensor_init_zero, roo_transceivers_Descriptor_Sensor_init_zero, roo_transceivers_Descriptor_Sensor_init_zero, roo_transceivers_Descriptor_Sensor_init_zero, roo_transceivers_Descriptor_Sensor_init_zero, roo_transceivers_Descriptor_Sensor_init_zero, roo_transceivers_Descriptor_Sensor_init_zero, roo_transceivers_Descriptor_Sensor_init_zero, roo_transceivers_Descriptor_Sensor_init_zero, roo_transceivers_Descriptor_Sensor_init_zero, roo_transceivers_Descriptor_Sensor_init_zero}, 0, {roo_transceivers_Descriptor_Actuator_init_zero, roo_transceivers_Descriptor_Actuator_init_zero, roo_transceivers_Descriptor_Actuator_init_zero, roo_transceivers_Descriptor_Actuator_init_zero, roo_transceivers_Descriptor_Actuator_init_zero, roo_transceivers_Descriptor_Actuator_init_zero, roo_transceivers_Descriptor_Actuator_init_zero, roo_transceivers_Descriptor_Actuator_init_zero, roo_transceivers_Descriptor_Actuator_init_zero, roo_transceivers_Descriptor_Actuator_init_zero, roo_transceivers_Descriptor_Actuator_init_zero, roo_transceivers_Descriptor_Actuator_init_zero, roo_transceivers_Descriptor_Actuator_init_zero, roo_transceivers_Descriptor_Actuator_init_zero, roo_transceivers_Descriptor_Actuator_init_zero, roo_transceivers_Descriptor_Actuator_init_zero}}
#define roo_transceivers_Descriptor_Sensor_init_zero {"", _roo_transceivers_Quantity_MIN}
#define roo_transceivers_Descriptor_Actuator_init_zero {"", _roo_transceivers_Quantity_MIN}
#define roo_transceivers_ClientMessage_init_zero {0, {roo_transceivers_ClientMessage_RequestUpdate_init_zero}}
#define roo_transceivers_ClientMessage_RequestUpdate_init_zero {0}
#define roo_transceivers_ClientMessage_RequestState_init_zero {0}
#define roo_transceivers_ClientMessage_Write_init_zero {"", "", "", 0}
#define roo_transceivers_ServerMessage_init_zero {0, {roo_transceivers_ServerMessage_UpdateBegin_init_zero}}
#define roo_transceivers_ServerMessage_UpdateBegin_init_zero {0}
#define roo_transceivers_ServerMessage_DescriptorAdded_init_zero {0, false, roo_transceivers_Descriptor_init_zero}
#define roo_transceivers_ServerMessage_DescriptorRemoved_init_zero {0}
#define roo_transceivers_ServerMessage_DeviceAdded_init_zero {"", "", 0}
#define roo_transceivers_ServerMessage_DeviceRemoved_init_zero {0}
#define roo_transceivers_ServerMessage_DevicePreserved_init_zero {0, false, 0}
#define roo_transceivers_ServerMessage_DeviceModified_init_zero {0, 0}
#define roo_transceivers_ServerMessage_UpdateEnd_init_zero {0}
#define roo_transceivers_ServerMessage_ReadingsBegin_init_zero {0}
#define roo_transceivers_ServerMessage_ReadingsEnd_init_zero {0}
#define roo_transceivers_ServerMessage_Reading_init_zero {"", "", 0, {roo_transceivers_ServerMessage_Reading_SensorValue_init_zero, roo_transceivers_ServerMessage_Reading_SensorValue_init_zero, roo_transceivers_ServerMessage_Reading_SensorValue_init_zero, roo_transceivers_ServerMessage_Reading_SensorValue_init_zero, roo_transceivers_ServerMessage_Reading_SensorValue_init_zero, roo_transceivers_ServerMessage_Reading_SensorValue_init_zero, roo_transceivers_ServerMessage_Reading_SensorValue_init_zero, roo_transceivers_ServerMessage_Reading_SensorValue_init_zero, roo_transceivers_ServerMessage_Reading_SensorValue_init_zero, roo_transceivers_ServerMessage_Reading_SensorValue_init_zero, roo_transceivers_ServerMessage_Reading_SensorValue_init_zero, roo_transceivers_ServerMessage_Reading_SensorValue_init_zero, roo_transceivers_ServerMessage_Reading_SensorValue_init_zero, roo_transceivers_ServerMessage_Reading_SensorValue_init_zero, roo_transceivers_ServerMessage_Reading_SensorValue_init_zero, roo_transceivers_ServerMessage_Reading_SensorValue_init_zero}}
#define roo_transceivers_ServerMessage_Reading_SensorValue_init_zero {"", 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define roo_transceivers_Descriptor_Sensor_id_tag 1
#define roo_transceivers_Descriptor_Sensor_quantity_tag 2
#define roo_transceivers_Descriptor_Actuator_id_tag 1
#define roo_transceivers_Descriptor_Actuator_quantity_tag 2
#define roo_transceivers_Descriptor_sensors_tag  3
#define roo_transceivers_Descriptor_actuators_tag 4
#define roo_transceivers_ClientMessage_Write_device_locator_schema_tag 1
#define roo_transceivers_ClientMessage_Write_device_locator_id_tag 2
#define roo_transceivers_ClientMessage_Write_device_locator_actuator_id_tag 3
#define roo_transceivers_ClientMessage_Write_value_tag 4
#define roo_transceivers_ClientMessage_request_update_tag 1
#define roo_transceivers_ClientMessage_request_state_tag 2
#define roo_transceivers_ClientMessage_write_tag 3
#define roo_transceivers_ServerMessage_UpdateBegin_delta_tag 1
#define roo_transceivers_ServerMessage_DescriptorAdded_key_tag 1
#define roo_transceivers_ServerMessage_DescriptorAdded_descriptor_tag 2
#define roo_transceivers_ServerMessage_DescriptorRemoved_key_tag 1
#define roo_transceivers_ServerMessage_DeviceAdded_locator_schema_tag 1
#define roo_transceivers_ServerMessage_DeviceAdded_locator_id_tag 2
#define roo_transceivers_ServerMessage_DeviceAdded_descriptor_key_tag 3
#define roo_transceivers_ServerMessage_DeviceRemoved_prev_index_tag 1
#define roo_transceivers_ServerMessage_DevicePreserved_prev_index_tag 1
#define roo_transceivers_ServerMessage_DevicePreserved_count_tag 2
#define roo_transceivers_ServerMessage_DeviceModified_prev_index_tag 1
#define roo_transceivers_ServerMessage_DeviceModified_descriptor_key_tag 3
#define roo_transceivers_ServerMessage_Reading_SensorValue_device_locator_sensor_id_tag 1
#define roo_transceivers_ServerMessage_Reading_SensorValue_value_tag 2
#define roo_transceivers_ServerMessage_Reading_SensorValue_age_ms_tag 3
#define roo_transceivers_ServerMessage_Reading_device_locator_schema_tag 1
#define roo_transceivers_ServerMessage_Reading_device_locator_id_tag 2
#define roo_transceivers_ServerMessage_Reading_sensor_values_tag 3
#define roo_transceivers_ServerMessage_transceiver_update_begin_tag 1
#define roo_transceivers_ServerMessage_descriptor_added_tag 2
#define roo_transceivers_ServerMessage_descriptor_removed_tag 3
#define roo_transceivers_ServerMessage_device_added_tag 5
#define roo_transceivers_ServerMessage_device_removed_tag 6
#define roo_transceivers_ServerMessage_device_preserved_tag 7
#define roo_transceivers_ServerMessage_device_modified_tag 8
#define roo_transceivers_ServerMessage_transceiver_update_end_tag 9
#define roo_transceivers_ServerMessage_readings_begin_tag 10
#define roo_transceivers_ServerMessage_reading_tag 11
#define roo_transceivers_ServerMessage_readings_end_tag 12

/* Struct field encoding specification for nanopb */
#define roo_transceivers_Descriptor_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  sensors,           3) \
X(a, STATIC,   REPEATED, MESSAGE,  actuators,         4)
#define roo_transceivers_Descriptor_CALLBACK NULL
#define roo_transceivers_Descriptor_DEFAULT NULL
#define roo_transceivers_Descriptor_sensors_MSGTYPE roo_transceivers_Descriptor_Sensor
#define roo_transceivers_Descriptor_actuators_MSGTYPE roo_transceivers_Descriptor_Actuator

#define roo_transceivers_Descriptor_Sensor_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   id,                1) \
X(a, STATIC,   SINGULAR, UENUM,    quantity,          2)
#define roo_transceivers_Descriptor_Sensor_CALLBACK NULL
#define roo_transceivers_Descriptor_Sensor_DEFAULT NULL

#define roo_transceivers_Descriptor_Actuator_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   id,                1) \
X(a, STATIC,   SINGULAR, UENUM,    quantity,          2)
#define roo_transceivers_Descriptor_Actuator_CALLBACK NULL
#define roo_transceivers_Descriptor_Actuator_DEFAULT NULL

#define roo_transceivers_ClientMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (contents,request_update,contents.request_update),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (contents,request_state,contents.request_state),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (contents,write,contents.write),   3)
#define roo_transceivers_ClientMessage_CALLBACK NULL
#define roo_transceivers_ClientMessage_DEFAULT NULL
#define roo_transceivers_ClientMessage_contents_request_update_MSGTYPE roo_transceivers_ClientMessage_RequestUpdate
#define roo_transceivers_ClientMessage_contents_request_state_MSGTYPE roo_transceivers_ClientMessage_RequestState
#define roo_transceivers_ClientMessage_contents_write_MSGTYPE roo_transceivers_ClientMessage_Write

#define roo_transceivers_ClientMessage_RequestUpdate_FIELDLIST(X, a) \

#define roo_transceivers_ClientMessage_RequestUpdate_CALLBACK NULL
#define roo_transceivers_ClientMessage_RequestUpdate_DEFAULT NULL

#define roo_transceivers_ClientMessage_RequestState_FIELDLIST(X, a) \

#define roo_transceivers_ClientMessage_RequestState_CALLBACK NULL
#define roo_transceivers_ClientMessage_RequestState_DEFAULT NULL

#define roo_transceivers_ClientMessage_Write_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_locator_schema,   1) \
X(a, STATIC,   SINGULAR, STRING,   device_locator_id,   2) \
X(a, STATIC,   SINGULAR, STRING,   device_locator_actuator_id,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    value,             4)
#define roo_transceivers_ClientMessage_Write_CALLBACK NULL
#define roo_transceivers_ClientMessage_Write_DEFAULT NULL

#define roo_transceivers_ServerMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (contents,transceiver_update_begin,contents.transceiver_update_begin),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (contents,descriptor_added,contents.descriptor_added),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (contents,descriptor_removed,contents.descriptor_removed),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (contents,device_added,contents.device_added),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (contents,device_removed,contents.device_removed),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (contents,device_preserved,contents.device_preserved),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (contents,device_modified,contents.device_modified),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (contents,transceiver_update_end,contents.transceiver_update_end),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (contents,readings_begin,contents.readings_begin),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (contents,reading,contents.reading),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (contents,readings_end,contents.readings_end),  12)
#define roo_transceivers_ServerMessage_CALLBACK NULL
#define roo_transceivers_ServerMessage_DEFAULT NULL
#define roo_transceivers_ServerMessage_contents_transceiver_update_begin_MSGTYPE roo_transceivers_ServerMessage_UpdateBegin
#define roo_transceivers_ServerMessage_contents_descriptor_added_MSGTYPE roo_transceivers_ServerMessage_DescriptorAdded
#define roo_transceivers_ServerMessage_contents_descriptor_removed_MSGTYPE roo_transceivers_ServerMessage_DescriptorRemoved
#define roo_transceivers_ServerMessage_contents_device_added_MSGTYPE roo_transceivers_ServerMessage_DeviceAdded
#define roo_transceivers_ServerMessage_contents_device_removed_MSGTYPE roo_transceivers_ServerMessage_DeviceRemoved
#define roo_transceivers_ServerMessage_contents_device_preserved_MSGTYPE roo_transceivers_ServerMessage_DevicePreserved
#define roo_transceivers_ServerMessage_contents_device_modified_MSGTYPE roo_transceivers_ServerMessage_DeviceModified
#define roo_transceivers_ServerMessage_contents_transceiver_update_end_MSGTYPE roo_transceivers_ServerMessage_UpdateEnd
#define roo_transceivers_ServerMessage_contents_readings_begin_MSGTYPE roo_transceivers_ServerMessage_ReadingsBegin
#define roo_transceivers_ServerMessage_contents_reading_MSGTYPE roo_transceivers_ServerMessage_Reading
#define roo_transceivers_ServerMessage_contents_readings_end_MSGTYPE roo_transceivers_ServerMessage_ReadingsEnd

#define roo_transceivers_ServerMessage_UpdateBegin_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     delta,             1)
#define roo_transceivers_ServerMessage_UpdateBegin_CALLBACK NULL
#define roo_transceivers_ServerMessage_UpdateBegin_DEFAULT NULL

#define roo_transceivers_ServerMessage_DescriptorAdded_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  descriptor,        2)
#define roo_transceivers_ServerMessage_DescriptorAdded_CALLBACK NULL
#define roo_transceivers_ServerMessage_DescriptorAdded_DEFAULT NULL
#define roo_transceivers_ServerMessage_DescriptorAdded_descriptor_MSGTYPE roo_transceivers_Descriptor

#define roo_transceivers_ServerMessage_DescriptorRemoved_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   key,               1)
#define roo_transceivers_ServerMessage_DescriptorRemoved_CALLBACK NULL
#define roo_transceivers_ServerMessage_DescriptorRemoved_DEFAULT NULL

#define roo_transceivers_ServerMessage_DeviceAdded_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   locator_schema,    1) \
X(a, STATIC,   SINGULAR, STRING,   locator_id,        2) \
X(a, STATIC,   SINGULAR, UINT32,   descriptor_key,    3)
#define roo_transceivers_ServerMessage_DeviceAdded_CALLBACK NULL
#define roo_transceivers_ServerMessage_DeviceAdded_DEFAULT NULL

#define roo_transceivers_ServerMessage_DeviceRemoved_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   prev_index,        1)
#define roo_transceivers_ServerMessage_DeviceRemoved_CALLBACK NULL
#define roo_transceivers_ServerMessage_DeviceRemoved_DEFAULT NULL

#define roo_transceivers_ServerMessage_DevicePreserved_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   prev_index,        1) \
X(a, STATIC,   OPTIONAL, UINT32,   count,             2)
#define roo_transceivers_ServerMessage_DevicePreserved_CALLBACK NULL
#define roo_transceivers_ServerMessage_DevicePreserved_DEFAULT NULL

#define roo_transceivers_ServerMessage_DeviceModified_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   prev_index,        1) \
X(a, STATIC,   SINGULAR, UINT32,   descriptor_key,    3)
#define roo_transceivers_ServerMessage_DeviceModified_CALLBACK NULL
#define roo_transceivers_ServerMessage_DeviceModified_DEFAULT NULL

#define roo_transceivers_ServerMessage_UpdateEnd_FIELDLIST(X, a) \

#define roo_transceivers_ServerMessage_UpdateEnd_CALLBACK NULL
#define roo_transceivers_ServerMessage_UpdateEnd_DEFAULT NULL

#define roo_transceivers_ServerMessage_ReadingsBegin_FIELDLIST(X, a) \

#define roo_transceivers_ServerMessage_ReadingsBegin_CALLBACK NULL
#define roo_transceivers_ServerMessage_ReadingsBegin_DEFAULT NULL

#define roo_transceivers_ServerMessage_ReadingsEnd_FIELDLIST(X, a) \

#define roo_transceivers_ServerMessage_ReadingsEnd_CALLBACK NULL
#define roo_transceivers_ServerMessage_ReadingsEnd_DEFAULT NULL

#define roo_transceivers_ServerMessage_Reading_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_locator_schema,   1) \
X(a, STATIC,   SINGULAR, STRING,   device_locator_id,   2) \
X(a, STATIC,   REPEATED, MESSAGE,  sensor_values,     3)
#define roo_transceivers_ServerMessage_Reading_CALLBACK NULL
#define roo_transceivers_ServerMessage_Reading_DEFAULT NULL
#define roo_transceivers_ServerMessage_Reading_sensor_values_MSGTYPE roo_transceivers_ServerMessage_Reading_SensorValue

#define roo_transceivers_ServerMessage_Reading_SensorValue_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_locator_sensor_id,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    value,             2) \
X(a, STATIC,   SINGULAR, UINT64,   age_ms,            3)
#define roo_transceivers_ServerMessage_Reading_SensorValue_CALLBACK NULL
#define roo_transceivers_ServerMessage_Reading_SensorValue_DEFAULT NULL

extern const pb_msgdesc_t roo_transceivers_Descriptor_msg;
extern const pb_msgdesc_t roo_transceivers_Descriptor_Sensor_msg;
extern const pb_msgdesc_t roo_transceivers_Descriptor_Actuator_msg;
extern const pb_msgdesc_t roo_transceivers_ClientMessage_msg;
extern const pb_msgdesc_t roo_transceivers_ClientMessage_RequestUpdate_msg;
extern const pb_msgdesc_t roo_transceivers_ClientMessage_RequestState_msg;
extern const pb_msgdesc_t roo_transceivers_ClientMessage_Write_msg;
extern const pb_msgdesc_t roo_transceivers_ServerMessage_msg;
extern const pb_msgdesc_t roo_transceivers_ServerMessage_UpdateBegin_msg;
extern const pb_msgdesc_t roo_transceivers_ServerMessage_DescriptorAdded_msg;
extern const pb_msgdesc_t roo_transceivers_ServerMessage_DescriptorRemoved_msg;
extern const pb_msgdesc_t roo_transceivers_ServerMessage_DeviceAdded_msg;
extern const pb_msgdesc_t roo_transceivers_ServerMessage_DeviceRemoved_msg;
extern const pb_msgdesc_t roo_transceivers_ServerMessage_DevicePreserved_msg;
extern const pb_msgdesc_t roo_transceivers_ServerMessage_DeviceModified_msg;
extern const pb_msgdesc_t roo_transceivers_ServerMessage_UpdateEnd_msg;
extern const pb_msgdesc_t roo_transceivers_ServerMessage_ReadingsBegin_msg;
extern const pb_msgdesc_t roo_transceivers_ServerMessage_ReadingsEnd_msg;
extern const pb_msgdesc_t roo_transceivers_ServerMessage_Reading_msg;
extern const pb_msgdesc_t roo_transceivers_ServerMessage_Reading_SensorValue_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define roo_transceivers_Descriptor_fields &roo_transceivers_Descriptor_msg
#define roo_transceivers_Descriptor_Sensor_fields &roo_transceivers_Descriptor_Sensor_msg
#define roo_transceivers_Descriptor_Actuator_fields &roo_transceivers_Descriptor_Actuator_msg
#define roo_transceivers_ClientMessage_fields &roo_transceivers_ClientMessage_msg
#define roo_transceivers_ClientMessage_RequestUpdate_fields &roo_transceivers_ClientMessage_RequestUpdate_msg
#define roo_transceivers_ClientMessage_RequestState_fields &roo_transceivers_ClientMessage_RequestState_msg
#define roo_transceivers_ClientMessage_Write_fields &roo_transceivers_ClientMessage_Write_msg
#define roo_transceivers_ServerMessage_fields &roo_transceivers_ServerMessage_msg
#define roo_transceivers_ServerMessage_UpdateBegin_fields &roo_transceivers_ServerMessage_UpdateBegin_msg
#define roo_transceivers_ServerMessage_DescriptorAdded_fields &roo_transceivers_ServerMessage_DescriptorAdded_msg
#define roo_transceivers_ServerMessage_DescriptorRemoved_fields &roo_transceivers_ServerMessage_DescriptorRemoved_msg
#define roo_transceivers_ServerMessage_DeviceAdded_fields &roo_transceivers_ServerMessage_DeviceAdded_msg
#define roo_transceivers_ServerMessage_DeviceRemoved_fields &roo_transceivers_ServerMessage_DeviceRemoved_msg
#define roo_transceivers_ServerMessage_DevicePreserved_fields &roo_transceivers_ServerMessage_DevicePreserved_msg
#define roo_transceivers_ServerMessage_DeviceModified_fields &roo_transceivers_ServerMessage_DeviceModified_msg
#define roo_transceivers_ServerMessage_UpdateEnd_fields &roo_transceivers_ServerMessage_UpdateEnd_msg
#define roo_transceivers_ServerMessage_ReadingsBegin_fields &roo_transceivers_ServerMessage_ReadingsBegin_msg
#define roo_transceivers_ServerMessage_ReadingsEnd_fields &roo_transceivers_ServerMessage_ReadingsEnd_msg
#define roo_transceivers_ServerMessage_Reading_fields &roo_transceivers_ServerMessage_Reading_msg
#define roo_transceivers_ServerMessage_Reading_SensorValue_fields &roo_transceivers_ServerMessage_Reading_SensorValue_msg

/* Maximum encoded size of messages (where known) */
#define ROO_TRANSCEIVERS_ROO_TRANSCEIVERS_PB_H_MAX_SIZE roo_transceivers_ServerMessage_size
#define roo_transceivers_ClientMessage_RequestState_size 0
#define roo_transceivers_ClientMessage_RequestUpdate_size 0
#define roo_transceivers_ClientMessage_Write_size 72
#define roo_transceivers_ClientMessage_size      74
#define roo_transceivers_Descriptor_Actuator_size 28
#define roo_transceivers_Descriptor_Sensor_size  28
#define roo_transceivers_Descriptor_size         960
#define roo_transceivers_ServerMessage_DescriptorAdded_size 969
#define roo_transceivers_ServerMessage_DescriptorRemoved_size 6
#define roo_transceivers_ServerMessage_DeviceAdded_size 48
#define roo_transceivers_ServerMessage_DeviceModified_size 12
#define roo_transceivers_ServerMessage_DevicePreserved_size 12
#define roo_transceivers_ServerMessage_DeviceRemoved_size 6
#define roo_transceivers_ServerMessage_Reading_SensorValue_size 41
#define roo_transceivers_ServerMessage_Reading_size 730
#define roo_transceivers_ServerMessage_ReadingsBegin_size 0
#define roo_transceivers_ServerMessage_ReadingsEnd_size 0
#define roo_transceivers_ServerMessage_UpdateBegin_size 2
#define roo_transceivers_ServerMessage_UpdateEnd_size 0
#define roo_transceivers_ServerMessage_size      972

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
